# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_grade', models.IntegerField(unique=True)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('station_type', models.CharField(choices=[('ES', 'Elementary School'), ('HS', 'High School'), ('DO', 'Division Office')], default='DO', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=32, unique=True)),
                ('qs_education', models.CharField(max_length=64)),
                ('qs_work_experience', models.IntegerField(help_text='Years of relevant experience')),
                ('qs_training', models.IntegerField(help_text='Hours of relevant training')),
                ('eligibility', models.CharField(choices=[('LET/PBET', 'LET/PBET'), ('PD907', 'PD 907'), ('CSC1', 'CSC LVL 1'), ('CSC2', 'CSC LVL 2')], default='LET/PBET', max_length=8)),
                ('is_open', models.BooleanField(default=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.Position')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.Station')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
            },
        ),
        migrations.AddField(
            model_name='position',
            name='salary_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.SalaryGrade'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together=set([('name', 'salary_grade')]),
        ),
    ]
