# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(blank=True, max_length=64, null=True)),
                ('station_type', models.CharField(choices=[('ES', 'Elementary'), ('HS', 'High School'), ('DO', 'Division Office')], default='DO', max_length=2)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('filled', models.BooleanField(default=False)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.Position')),
            ],
        ),
        migrations.CreateModel(
            name='ItemHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=64, null=True)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=64)),
                ('work_experience', models.IntegerField(help_text='Years of relevant experience')),
                ('training', models.IntegerField(help_text='Hours of relevant training')),
                ('eligibility', models.CharField(choices=[('LET/PBET', 'LET/PBET'), ('PD907', 'PD 907'), ('CSC1', 'CSC LVL 1'), ('CSC2', 'CSC LVL 2')], default='LET/PBET', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vacancy.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='eligibility',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='item_number',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='position',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='qs_education',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='qs_training',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='qs_work_experience',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='station',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Station',
        ),
        migrations.AddField(
            model_name='itemhistory',
            name='appointee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vacancy.Person'),
        ),
        migrations.AddField(
            model_name='itemhistory',
            name='incumbent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vacancy.Person'),
        ),
        migrations.AddField(
            model_name='itemhistory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.Item'),
        ),
        migrations.AddField(
            model_name='position',
            name='qualifications',
            field=models.ManyToManyField(related_name='_position_qualifications_+', to='vacancy.Qualification'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='items',
            field=models.ManyToManyField(to='vacancy.Item'),
        ),
    ]
