# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_auto_20160310_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarygrade',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
