# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0005_auto_20160310_0532'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='position',
            unique_together=set([]),
        ),
    ]
