# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0006_auto_20160310_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='qualifications',
            field=models.ManyToManyField(blank=True, null=True, to='vacancy.Qualification'),
        ),
    ]
