# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0007_auto_20160310_0549'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=64)),
                ('work_experience', models.IntegerField(help_text='Years of relevant experience')),
                ('training', models.IntegerField(help_text='Hours of relevant training')),
                ('eligibility', models.CharField(choices=[('LET/PBET', 'LET/PBET'), ('PD907', 'PD 907'), ('CSC1', 'CSC LVL 1'), ('CSC2', 'CSC LVL 2')], default='LET/PBET', max_length=8)),
            ],
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='education',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='position',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='eligibility',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='training',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='qualificationvalue',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.Qualification'),
        ),
    ]
