# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0008_auto_20160310_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualificationvalue',
            old_name='qualification',
            new_name='qs',
        ),
    ]
