# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0009_auto_20160310_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='qs',
            field=models.ManyToManyField(through='vacancy.QualificationValue', to='vacancy.Qualification'),
        ),
        migrations.AddField(
            model_name='qualificationvalue',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancy.Position'),
        ),
        migrations.AlterField(
            model_name='qualificationvalue',
            name='qs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancy.Qualification'),
        ),
    ]
