# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0013_auto_20160310_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualificationvalue',
            name='position',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vacancy.Position'),
        ),
        migrations.AlterField(
            model_name='qualificationvalue',
            name='qualification',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vacancy.Qualification'),
        ),
    ]
