# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0015_auto_20160311_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='category',
            field=models.CharField(choices=[('TS', 'Teaching Staff'), ('NTS', 'Non-Teaching Staff'), ('TR', 'Teaching-Related')], default='TS', max_length=8),
        ),
    ]
