# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0016_position_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
