# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0017_item_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='station_type',
            field=models.CharField(choices=[('ES', 'Elementary'), ('HS', 'High School'), ('DO', 'Division Office')], default='ES', max_length=2),
        ),
    ]
