# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0018_auto_20160315_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualificationvalue',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancy.Qualification'),
        ),
    ]
