# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0019_auto_20160315_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualificationvalue',
            name='notes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='Newly created item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='station_type',
            field=models.CharField(choices=[('ES', 'Elementary'), ('HS', 'High School'), ('SDS', 'Office of the Schools Division Superintendent'), ('CID', 'Curriculum Implementation Division'), ('SGOD', 'School Governance and Operations Division')], default='ES', max_length=2),
        ),
        migrations.AlterField(
            model_name='qualificationvalue',
            name='eligibility',
            field=models.CharField(choices=[('LET/PBET', 'LET/PBET'), ('NQESH', 'LET/PBET + National Qualifying Exam for School Heads'), ('PD907', 'PD 907'), ('CSC1', 'CSC LVL 1'), ('CSC2', 'CSC LVL 2'), ('CESO', 'CESO')], default='LET/PBET', max_length=8),
        ),
    ]
