# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0020_auto_20160317_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualificationvalue',
            name='eligibility',
            field=models.CharField(choices=[('LET/PBET', 'LET/PBET'), ('PD907', 'PD 907'), ('CSC1', 'CSC LVL 1'), ('CSC2', 'CSC LVL 2'), ('CESO', 'CESO')], default='LET/PBET', max_length=8),
        ),
    ]
