# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0022_auto_20160321_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='close_date',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='pub_date',
        ),
    ]
