# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 13:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0023_auto_20160322_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_appointed', models.DateField(blank=True, null=True)),
                ('nature', models.CharField(choices=[('ORG', 'Original'), ('PRM', 'Promotion'), ('TRN', 'Transfer'), ('REM', 'Re-employment'), ('REA', 'Reappointment'), ('REC', 'Reclassification'), ('DEM', 'Demotion')], default='ORG', max_length=3)),
                ('status', models.CharField(choices=[('PMT', 'Permanent'), ('SUB', 'Substitute')], default='PMT', max_length=3)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='itemhistory',
            name='appointee',
        ),
        migrations.RemoveField(
            model_name='itemhistory',
            name='incumbent',
        ),
        migrations.RemoveField(
            model_name='itemhistory',
            name='item',
        ),
        migrations.RenameField(
            model_name='registry',
            old_name='score',
            new_name='points',
        ),
        migrations.AddField(
            model_name='person',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='person',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='person',
            name='name_ext',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+639191234567'. Up to 12 digits allowed.", regex='^\\+?1?\\d{11,12}$')]),
        ),
        migrations.AddField(
            model_name='registry',
            name='core_subject',
            field=models.CharField(choices=[('ENG', 'English'), ('SCI', 'Science'), ('MTH', 'Mathematics'), ('FIL', 'Filipino')], default='ENG', max_length=3),
        ),
        migrations.AddField(
            model_name='registry',
            name='school',
            field=models.CharField(choices=[('ES', 'Elementary'), ('HS', 'High School')], default='ES', max_length=2),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='ItemHistory',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vacancy.Person'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.Item'),
        ),
    ]
