# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0024_auto_20160323_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_appointed',
            field=models.DateField(),
        ),
    ]
