# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0029_auto_20160502_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
