# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0030_auto_20160502_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='school_year',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vacancy.SchoolYear'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='registry',
            unique_together=set([('person', 'school_year')]),
        ),
    ]
