# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0031_auto_20160502_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tranche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrancheSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranche_no', models.IntegerField()),
                ('year', models.IntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='salarygrade',
            name='monthly_salary',
        ),
        migrations.AddField(
            model_name='tranchesalary',
            name='salary_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranche_salary', to='vacancy.SalaryGrade'),
        ),
        migrations.AddField(
            model_name='tranchesalary',
            name='tranche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancy.Tranche'),
        ),
        migrations.AlterUniqueTogether(
            name='tranchesalary',
            unique_together=set([('salary_grade', 'year')]),
        ),
    ]
