# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0032_auto_20160504_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualificationvalue',
            name='education',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='qualificationvalue',
            name='eligibility',
            field=models.CharField(choices=[('LET/PBET', 'LET/PBET'), ('RA1080', 'RA 1080'), ('PD907', 'PD 907'), ('CSC1', 'CSC LVL 1'), ('CSC2', 'CSC LVL 2'), ('CESO', 'CESO')], default='LET/PBET', max_length=8),
        ),
        migrations.AlterField(
            model_name='qualificationvalue',
            name='training',
            field=models.CharField(help_text='Relevant training', max_length=512),
        ),
        migrations.AlterField(
            model_name='qualificationvalue',
            name='work_experience',
            field=models.CharField(max_length=512),
        ),
    ]
